name: mcdo_paris
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.5
  flutter_svg: any
  hive: ">=2.2.3 <2.3.0"
  hive_flutter: ">=1.1.0 <1.2.0"
  map_launcher: ^2.3.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo-mcdo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21